version: '3.8'

services:
 web:
  build:
   context: .
  depends_on:
    - postgresdb
  entrypoint: ./start.sh
  environment:
    - initial=${initial}
  ports:
  - 8000:8000
  volumes:
  - ./:/app

 postgresdb:
  image: postgres
  ports:
  - 5432:5432
  healthcheck:
    test: ["CMD", "psql", "-U", "postgres"]
    interval: 1m30s
    timeout: 10s
    retries: 3
    start_period: 40s

  environment:
  - POSTGRES_PASSWORD=peri54ri7end