# Generated by Django 4.1.5 on 2023-02-09 11:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_article_text_article_content_article_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Title', max_length=300),
        ),
    ]
