# Generated by Django 4.1.5 on 2023-02-11 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_preview_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pud_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
