# Generated by Django 4.1.5 on 2023-02-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_pud_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pud_date',
            new_name='pub_date',
        ),
    ]
